# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

In [ ]:
# complete your program here
f_str = input('Please enter the temperature in Fahrenheit: ')
f = float(f_str)

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 140
140.0
140.0F is 60.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
# complete your program here
c_str = input('Please enter the temperature in Celsius: ')
c = float(c_str)
f = (c * 9/5) + 32
print(f'{c}C is {f:.1f} in Fahrenheit.')

Please enter the temperature in Celsius: 50
50.0C is 122.0 in Fahrenheit.


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')
temp = float(d)
if m == 'C':
    f = (temp * 9/5) + 32
    print(f'{temp}C is {f} in Fahrenheit')
elif m == 'F':
    c = (temp - 32) * 5/9
    print(f'{temp}F is {c} in Celsius')
else:
    print("Invalid unit. Please enter C or F.")


Please enter the temperature: 100
Is this in Celsius or Fahrenheit? c
Invalid unit. Please enter C or F.


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
print(len(sentence))

48


In [ ]:
# Convert the whole string to lower case.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
print(sentence[9:-9])

heap. Show me the code - Linus


In [ ]:
# Split the sentence into a list of substrings by space ' '.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
print(sentence.split())

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [ ]:
# Given the sentence, output a list of words in lowercase (without punctuations).
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
clean_string = sentence.replace('.', '').replace('-', '').lower()
words_no_punc = clean_string.split()
print(words_no_punc)




['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [ ]:
# Count the total number of vowels in the sentence.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"
vowels = 'aeiou'
count = 0
for char in sentence:
    if char in vowels:
        count += 1
print(count)

13


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
for i in range(len(sentence)):
  sentence = "Talk is cheap. Show me the code - Linus Torvalds"
  vowels = 'aeiouAEIOU'

# The list comprehension:
# 'i' is the index, 'char' is the letter. We only keep 'i' if 'char' is a vowel.
vowel_indices = [i for i, char in enumerate(sentence) if char in vowels]

print(vowel_indices)


[1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range (5):
    cubes.append(i**3)
print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Use list comprehension to create the same list
cubes = [i**3 for i in range(5)]
print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowels = 'aeiou'
[i for i in range(len(sentence)) if sentence[i] in vowels]

[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]

In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = int(input('How many numbers do you want? '))

# Your loop logic is perfect!
for i in range(n):
    if i == 0:
        fibonacci.append(0)
    elif i == 1:
        fibonacci.append(1)
    else:
        # Calculate the sum of the two previous elements
        next_number = fibonacci[i-1] + fibonacci[i-2]
        fibonacci.append(next_number)

print(fibonacci)

How many numbers do you want? 1
[0]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {
    'Pfizer': 0.95,
    'Moderna': 0.95,
    'AstraZeneca': 0.72,
    'Johnson & Johnson': 0.66
}

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66}


In [ ]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
if v in v_dict:
    print(v_dict[v])


Which vaccine? Moderna
0.95


In [ ]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [ ]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914, 'Sinovac': 0.5038}


In [ ]:
# Print vaccines with efficacy lower than 90%.
v=input('Which vaccine? ')
print("Vaccines with < 90% efficacy:")
for name, efficacy in v_dict.items():
    if efficacy < 0.90:
        print(name)


Which vaccine? AstraZeneca
Vaccines with < 90% efficacy:
AstraZeneca
Johnson & Johnson


In [ ]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [ ]:
# Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}

# Use a loop to iterate all characters
for char in sentence:
    # 1. Check if the character is NOT a space
    if char != ' ':
        # 2. If it's already in the dictionary, add 1 to the count
        if char in ch_dict:
            ch_dict[char] += 1
        # 3. If it's the first time we see the letter, set count to 1
        else:
            ch_dict[char] = 1

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [ ]:
import numpy as np

In [ ]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
arr = np.arange(2, 40, 2)
arr = np.array(arr)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [ ]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([])
arr = np.arange(1, 40, 2)
arr = np.array(arr)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [ ]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
M = np.random.normal(0, 1, (10, 10))
M.shape
arr = np.arange(100).reshape(10, 10)
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
arr = np.random.randn(10, 10)
arr


array([[-1.28036761, -0.3422234 , -0.74866599, -0.06954413, -0.24578125,
         1.31703636, -0.00948932,  2.08623586,  0.60434494, -0.93984041],
       [-0.56667187,  0.2502533 ,  1.13161824, -0.26233011,  1.41879552,
         0.73139274, -0.11787308, -0.79718165,  1.37962458, -1.09617601],
       [-0.52413919, -0.55879623, -0.57836337,  0.99972514, -1.34470918,
         0.92269949, -0.08278044, -0.68600925, -0.16528796,  0.71631389],
       [ 1.67077147,  1.30524441, -0.60584294, -1.32407456,  0.70936046,
         0.30781343,  0.90177219, -0.605097  ,  0.81107907, -0.67443745],
       [-1.4150641 , -0.68633759,  0.66684997,  1.14352887,  0.06232004,
        -2.49370743, -0.90285053,  0.74386187,  0.48462707,  0.51167202],
       [ 1.13767397, -0.13448099,  0.73159654,  0.32694581,  1.82059142,
        -0.79645525,  0.5292442 ,  0.226274  ,  0.26300672, -1.67826345],
       [ 0.88932621,  0.92467196,  0.08691143, -0.97393137,  0.00394414,
        -1.31785317,  0.39961166, -1.54538962

In [ ]:
# Count the numbers in M with an absolute value greater than 1
count_abs_greater_than_1 = np.sum(np.abs(arr) > 1)
count

13

In [ ]:
5# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of rows (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().
r = int(input('Row count: '))
c = int(input('column count: '))
# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, (r, c))
arr

Row count: 4
column count: 5
Row count: 6
column count: 7


array([[13, 17, 16, 16, 15, 15, 12],
       [14, 13, 17, 18, 14, 19, 14],
       [15, 15, 18, 19, 11, 17, 13],
       [17, 16, 17, 15, 18, 11, 18],
       [13, 12, 10, 15, 15, 13, 13],
       [15, 12, 14, 10, 10, 10, 16]])

In [ ]:
# output the element in the first row and the third column
print(arr[0, 2])

16


In [ ]:
# output the element in the second row and the last column
print(arr[1, -1])


14


In [ ]:
# output the second row of the array
print(arr[1, :])

[14 13 17 18 14 19 14]


In [ ]:
# output the second last row of the array
print(arr[-2, :])

[13 12 10 15 15 13 13]


In [ ]:
# output the second column of the array
print(arr[:, 1])

[17 13 15 16 12 12]


In [ ]:
# output the second last column of the array
print(arr[:, -2])


[15 19 17 11 13 10]


In [ ]:
# output the upper-left 3x3 sub-array
print(arr[:3, :3])

[[13 17 16]
 [14 13 17]
 [15 15 18]]


In [ ]:
# output the bottom-left 3x3 sub-array
print(arr[-3:, :3])

[[17 16 17]
 [13 12 10]
 [15 12 14]]


In [ ]:
# output the upper-right 3x3 sub-array
print(arr[:3, -3:])

[[15 15 12]
 [14 19 14]
 [11 17 13]]


In [ ]:
# output the bottom-right 3x3 sub-array
print(arr[-3:, -3:])

[[18 11 18]
 [15 13 13]
 [10 10 16]]


In [ ]:
# Create a 1-D array from 1 to 50 (inclusive)
A = ...
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A = np.arange(1, 51)
A = A.reshape(5, 10)
print(A)


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [ ]:
# add a row [51,...,60] to A
row = np.arange(51, 61)
A = np.vstack([A, row])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
split = np.hsplit(A, [3])
A1 = split[0]
A2 = split[1]

In [ ]:
# Add 10 to each element of A
add = A + 10
print(add)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [ ]:
# Calculate the square root of each element in A
root = np.sqrt(A)
print(root)

[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
  2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]
 [6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]]


In [ ]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
print(np.sqrt(A))

[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
  2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]
 [6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]]


In [ ]:
# Print the mean, standard devietion of all numbers in M
mean = np.mean(A)
std = np.std(A)
print(mean)
print(std)


30.5
17.318102282486574


In [ ]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print("Maximum value in M: ", np.max(M))
print("3rd Quartile (75%): ", np.percentile(M, 75))
print("Median (50%):       ", np.median(M))
print("1st Quartile (25%): ", np.percentile(M, 25))
print("Minimum value in M: ", np.min(M))


Maximum value in M:  2.649481064778545
3rd Quartile (75%):  0.9141844115567195
Median (50%):        0.13229762618868718
1st Quartile (25%):  -0.5149898087518825
Minimum value in M:  -2.780117825900196
